var dimse_8h =
[
    [ "T_DIMSE_C_StoreRQ", "struct_t___d_i_m_s_e___c___store_r_q.html", null ],
    [ "T_DIMSE_C_StoreRSP", "struct_t___d_i_m_s_e___c___store_r_s_p.html", null ],
    [ "T_DIMSE_C_EchoRQ", "struct_t___d_i_m_s_e___c___echo_r_q.html", null ],
    [ "T_DIMSE_C_EchoRSP", "struct_t___d_i_m_s_e___c___echo_r_s_p.html", null ],
    [ "T_DIMSE_C_FindRQ", "struct_t___d_i_m_s_e___c___find_r_q.html", null ],
    [ "T_DIMSE_C_FindRSP", "struct_t___d_i_m_s_e___c___find_r_s_p.html", null ],
    [ "T_DIMSE_C_GetRQ", "struct_t___d_i_m_s_e___c___get_r_q.html", null ],
    [ "T_DIMSE_C_GetRSP", "struct_t___d_i_m_s_e___c___get_r_s_p.html", null ],
    [ "T_DIMSE_C_MoveRQ", "struct_t___d_i_m_s_e___c___move_r_q.html", null ],
    [ "T_DIMSE_C_MoveRSP", "struct_t___d_i_m_s_e___c___move_r_s_p.html", null ],
    [ "T_DIMSE_C_CancelRQ", "struct_t___d_i_m_s_e___c___cancel_r_q.html", null ],
    [ "T_DIMSE_N_EventReportRQ", "struct_t___d_i_m_s_e___n___event_report_r_q.html", null ],
    [ "T_DIMSE_N_EventReportRSP", "struct_t___d_i_m_s_e___n___event_report_r_s_p.html", null ],
    [ "T_DIMSE_N_GetRQ", "struct_t___d_i_m_s_e___n___get_r_q.html", null ],
    [ "T_DIMSE_N_GetRSP", "struct_t___d_i_m_s_e___n___get_r_s_p.html", null ],
    [ "T_DIMSE_N_SetRQ", "struct_t___d_i_m_s_e___n___set_r_q.html", null ],
    [ "T_DIMSE_N_SetRSP", "struct_t___d_i_m_s_e___n___set_r_s_p.html", null ],
    [ "T_DIMSE_N_ActionRQ", "struct_t___d_i_m_s_e___n___action_r_q.html", null ],
    [ "T_DIMSE_N_ActionRSP", "struct_t___d_i_m_s_e___n___action_r_s_p.html", null ],
    [ "T_DIMSE_N_CreateRQ", "struct_t___d_i_m_s_e___n___create_r_q.html", null ],
    [ "T_DIMSE_N_CreateRSP", "struct_t___d_i_m_s_e___n___create_r_s_p.html", null ],
    [ "T_DIMSE_N_DeleteRQ", "struct_t___d_i_m_s_e___n___delete_r_q.html", null ],
    [ "T_DIMSE_N_DeleteRSP", "struct_t___d_i_m_s_e___n___delete_r_s_p.html", null ],
    [ "T_DIMSE_Message", "struct_t___d_i_m_s_e___message.html", null ],
    [ "T_DIMSE_StoreProgress", "struct_t___d_i_m_s_e___store_progress.html", null ],
    [ "T_DIMSE_DetectedCancelParameters", "struct_t___d_i_m_s_e___detected_cancel_parameters.html", null ],
    [ "DIMSE_createFilestream", "dimse_8h.html#ae4a51f6e2fa145400aea97c0db665bfb", null ],
    [ "DIMSE_ignoreDataSet", "dimse_8h.html#a48991c10e22e4b79074b206cd4c48d19", null ],
    [ "DIMSE_receiveCommand", "dimse_8h.html#af017f54bd91b6312ce036f14091bb94c", null ],
    [ "DIMSE_receiveDataSetInFile", "dimse_8h.html#aacac2db27e78e7a0564b3de7e8d755b0", null ],
    [ "DIMSE_receiveDataSetInMemory", "dimse_8h.html#a1c8af7c1373f464e1234b5adeaf7c0eb", null ],
    [ "DIMSE_sendMessageUsingFileData", "dimse_8h.html#a033aff53647944b9f566ef314fc2a0a0", null ],
    [ "DIMSE_sendMessageUsingMemoryData", "dimse_8h.html#a0d34bb11461b5a8e4e27a89f6355bd1c", null ],
    [ "dcmMaxOutgoingPDUSize", "dimse_8h.html#aa6190e80986355abf18aeac105a6d8d4", null ],
    [ "dcmPeerRequiresExactUIDCopy", "dimse_8h.html#aa206bbf52c32e96820c5def5a34d5be9", null ]
];