var topics =
[
    [ "OFvisit &ndash; OFvariant", "group__ofvisit__variant.html", null ],
    [ "OFget &ndash; OFvariant", "group__ofget__variant.html", null ],
    [ "The XML parser", "group___x_m_l_parser_general.html", "group___x_m_l_parser_general" ],
    [ "Configuring CGNS Internals; valid cg_configure() options.", "group___c_g_n_s_internals___f_n_c___c_g___c_o_n_f_i_g.html", "group___c_g_n_s_internals___f_n_c___c_g___c_o_n_f_i_g" ],
    [ "Information Keys", "group___information_keys.html", "group___information_keys" ],
    [ "Global array typedefs", "group__arraytypedefs.html", null ],
    [ "Global matrix typedefs", "group__matrixtypedefs.html", null ],
    [ "Flags", "group__flags.html", "group__flags" ],
    [ "Enumerations", "group__enums.html", "group__enums" ],
    [ "Variables controlling the file creation mode.", "group___file_vars.html", "group___file_vars" ],
    [ "Variables controlling the compression, name size, and integer size.", "group___file_options.html", "group___file_options" ],
    [ "maximum string lengths;", "group___string_lengths.html", "group___string_lengths" ],
    [ "Structures used by external API functions.", "group___a_p_i_structs.html", "group___a_p_i_structs" ],
    [ "Error return codes - exerrval return values", "group___error_return_codes.html", "group___error_return_codes" ],
    [ "Internal Functions and Defines", "group___internal.html", null ],
    [ "Variables controlling storage of reduction variables", "group___reduction_variables.html", "group___reduction_variables" ],
    [ "vtkGenericDataArray Concept Methods", "group__vtk_g_d_a_concept_methods.html", "group__vtk_g_d_a_concept_methods" ],
    [ "Streams used for IOSS output", "group___ioss_streams.html", "group___ioss_streams" ],
    [ "Data types for ISO19111 C API", "group__iso19111__types.html", "group__iso19111__types" ],
    [ "Binding in C of basic methods from the C++ API", "group__iso19111__functions.html", null ],
    [ "Binding in C of advanced methods from the C++ API", "group__advanced__cpp__binding.html", "group__advanced__cpp__binding" ],
    [ "Functions Shared by Encode and Decode", "group__basefuncs.html", null ],
    [ "Legacy pre-1.0 C API", "group__oldfuncs.html", "group__oldfuncs" ],
    [ "Functions for Decoding", "group__decfuncs.html", null ],
    [ "Functions for Encoding", "group__encfuncs.html", null ],
    [ "MPI", "group___m_p_i.html", "group___m_p_i" ],
    [ "Serialization", "group___serialization.html", "group___serialization" ],
    [ "Geometry_Module", "group___geometry___module.html", "group___geometry___module" ],
    [ "Utilities", "group___utilities.html", null ],
    [ "ResultsData", "group___results_data.html", null ],
    [ "ModelDescription", "group___model_description.html", "group___model_description" ]
];