var searchData=
[
  ['uc_2002_3a_20select_20patient_20from_20worklist_20detailed_0',['4.2 UC-02: Select Patient from Worklist (Detailed)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md245',1,'']]],
  ['uc_2003_3a_20capture_20image_20detailed_1',['4.4 UC-03: Capture Image (Detailed)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md247',1,'']]],
  ['ui_2',['Epic 3: Procedure-Based Patient Addition UI',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2docs_2_e_p_i_c___s_t_a_t_u_s___s_u_m_m_a_r_y.html#autotoc_md180',1,'']]],
  ['ui_3',['Step 1: Add VTK Widget to ExamPage.ui',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md562',1,'']]],
  ['ui_20configuration_4',['UI Configuration',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_205-_settings-_configuration.html#autotoc_md457',1,'']]],
  ['ui_20design_5',['UI Design',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html',1,'Procedure-Based Patient Addition UI Design'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md709',1,'UI Design']]],
  ['ui_20enhancements_6',['Phase 7: UI Enhancements',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_207-_examination-_workflow-_design.html#autotoc_md541',1,'']]],
  ['ui_20only_20builder_20no_20repository_7',['Pattern 1: Simple UI-Only Builder (No Repository)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_204-_builder-_pattern.html#autotoc_md411',1,'']]],
  ['under_20linux_20unix_8',['Debugging under LINUX/UNIX',['../xmlparser.html#xmlparser_debuglinux',1,'']]],
  ['under_20windows_9',['Debugging under WINDOWS',['../xmlparser.html#xmlparser_debugwin',1,'']]],
  ['unique_20device_20package_20issues_10',['Unique Device Package Issues',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md160',1,'']]],
  ['unit_20tests_11',['Unit Tests',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md727',1,'']]],
  ['unit_20tests_20needed_12',['Unit Tests Needed',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md576',1,'']]],
  ['unix_13',['Debugging under LINUX/UNIX',['../xmlparser.html#xmlparser_debuglinux',1,'']]],
  ['unsatisfied_20requirements_14',['Unsatisfied Requirements',['../requirements.html#missing_satisfies',1,'']]],
  ['unverified_20requirements_15',['Unverified Requirements',['../requirements.html#missing_verifies',1,'']]],
  ['upcoming_20features_16',['Upcoming features',['../classvtk_i_o_s_s_writer.html#UpcomingFeatures',1,'']]],
  ['update_17',['Update',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_207-_examination-_workflow-_design.html#autotoc_md528',1,'4. Worklist Status Update'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md568',1,'Step 3: Worklist Status Update']]],
  ['uri_18',['Base URI',['../classvtk_u_r_i_loader.html#autotoc_md1024',1,'']]],
  ['url_20manipulation_20routines_19',['URL Manipulation Routines',['../classvtksys_1_1_system_tools.html#autotoc_md1021',1,'']]],
  ['usage_20',['Usage',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md141',1,'⚠️ OBSERVATION: Inconsistent Namespace Usage'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md122',1,'✅ GOOD: Smart Pointer Usage'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_209-_context_manager.html#autotoc_md592',1,'Usage'],['../classvtk_data_set_attributes_field_list.html#Usage',1,'Usage']]],
  ['usage_21',['usage',['../xmlparser.html#xmlparser_example',1,'Advanced Tutorial and Many Examples of usage.'],['../classvtk_u_r_i_loader.html#autotoc_md1025',1,'Basic usage']]],
  ['usage_20in_20delegates_22',['Context Usage in Delegates',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md517',1,'']]],
  ['usage_20in_20readers_23',['Usage in readers',['../classvtk_u_r_i_loader.html#autotoc_md1026',1,'']]],
  ['usage_3a_20how_20to_20include_20the_20xmlparser_20library_20inside_20your_20project_24',['General usage: How to include the XMLParser library inside your project.',['../xmlparser.html#xmlparser_usage',1,'']]],
  ['use_20case_25',['Example of use case',['../classvtk_data_object_mesh_cache.html#autotoc_md796',1,'']]],
  ['use_20cases_26',['Use Cases',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md243',1,'4. Scenarios (Use Cases)'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md244',1,'4.1 Primary Use Cases']]],
  ['use_20this_20filter_27',['How To Use This Filter',['../classvtk_continuous_scatterplot.html#vtkContinuousScatterplot-how-to-use',1,'']]],
  ['use_20this_20filter_28',['to use this filter',['../classvtk_fiber_surface.html#How',1,'']]],
  ['used_29',['✅ OBSERVATION: No Pimpl Pattern Used',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md130',1,'']]],
  ['used_20in_20core_20package_30',['✅ GOOD: No pimpl pattern used in Core package',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md76',1,'']]],
  ['user_20acceptance_20criteria_31',['User Acceptance Criteria',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md729',1,'']]],
  ['user_20action_32',['Lazy Page Construction (User Action)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_204-_builder-_pattern.html#autotoc_md424',1,'']]],
  ['user_20entity_33',['User Entity',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md477',1,'']]],
  ['user_20interactions_34',['9. User Interactions',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md657',1,'']]],
  ['user_20login_35',['Phase 2: User Login',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md476',1,'']]],
  ['user_5froles_36',['user_roles',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html#autotoc_md290',1,'']]],
  ['users_37',['users',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html#autotoc_md288',1,'']]],
  ['uses_20qreadwritelock_20correctly_20l61_20l66_20l85_38',['✅ GOOD: LoggerProvider uses QReadWriteLock correctly (L61, L66, L85)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md71',1,'']]],
  ['using_20namespace_20violations_20in_20headers_39',['Using Namespace Violations in Headers',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md38',1,'1. Using Namespace Violations in Headers'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md97',1,'1. Using Namespace Violations in Headers']]],
  ['using_20verdict_40',['Using Verdict',['../C:/Users/altay/OneDrive/Projects/etrek/ThirdPartyLibraries/vtk/include/vtk-9.5/vtkverdict/verdict.h#UsingVerdict',1,'']]]
];
