var searchData=
[
  ['table_20models_0',['Custom Table Models',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_203-_model-_view-_delegate-_pattern.html#autotoc_md377',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md463',1,'Table of Contents'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md612',1,'Table of Contents'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md740',1,'Table of Contents']]],
  ['table_20options_2',['Lookup Table Options',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_205-_settings-_configuration.html#autotoc_md452',1,'']]],
  ['table_20schema_3',['Table Schema',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_205-_settings-_configuration.html#autotoc_md449',1,'']]],
  ['tables_4',['Tables',['../classvtk_fiber_surface.html#Case',1,'']]],
  ['tabs_5',['Settings Tabs',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_205-_settings-_configuration.html#autotoc_md458',1,'']]],
  ['tags_20reference_6',['9. Common Doxygen Tags Reference',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md774',1,'']]],
  ['target_20hardware_7',['2.1 Target Hardware',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md233',1,'']]],
  ['task_20mapping_8',['5. MWL Task Mapping',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_207-_examination-_workflow-_design.html#autotoc_md529',1,'']]],
  ['task_20mapping_20repository_9',['Epic 5: MWL Task Mapping Repository',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2docs_2_e_p_i_c___s_t_a_t_u_s___s_u_m_m_a_r_y.html#autotoc_md191',1,'']]],
  ['tasks_10',['Completed Tasks',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md546',1,'']]],
  ['technical_20documentation_11',['ImageViewer Technical Documentation',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html',1,'']]],
  ['technique_5fparameters_12',['technique_parameters',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html#autotoc_md316',1,'']]],
  ['technologies_13',['Key Technologies',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_c_l_a_u_d_e.html#autotoc_md15',1,'']]],
  ['template_14',['Template',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md742',1,'1. File Header Template'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_204-_builder-_pattern.html#autotoc_md400',1,'IWidgetDelegateBuilder Template']]],
  ['template_20block_20comment_20for_20complex_20members_20_3a_15',['Template (Block comment for complex members):',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md759',1,'']]],
  ['template_20in_20line_20_3a_16',['Template (In-line):',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md758',1,'']]],
  ['template_3a_17',['Template:',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md746',1,'Template:'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md752',1,'Template:'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_212-_doxygen-_documentation-_standards.html#autotoc_md763',1,'Template:']]],
  ['testing_20plan_18',['Testing Plan',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md575',1,'Testing Plan'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md726',1,'Testing Plan']]],
  ['testing_20scenarios_19',['Manual Testing Scenarios',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md578',1,'']]],
  ['tests_20',['Tests',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md728',1,'Integration Tests'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_c_l_a_u_d_e.html#autotoc_md6',1,'Tests'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md727',1,'Unit Tests']]],
  ['tests_20needed_21',['Tests Needed',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md577',1,'Integration Tests Needed'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md576',1,'Unit Tests Needed']]],
  ['tetrahedra_20with_20grey_20cases_22',['tetrahedra with grey cases',['../classvtk_fiber_surface.html#Marching',1,'']]],
  ['the_20base_20fiber_20surface_23',['cases of the base fiber surface',['../classvtk_fiber_surface.html#Clipping',1,'']]],
  ['the_20following_20concept_20requirements_3a_24',['class satisfies the following concept requirements:',['../requirements.html#The',1,'']]],
  ['the_20heartbeat_20output_25',['Properties for the heartbeat output',['../index.html#autotoc_md1001',1,'']]],
  ['the_20libjpeg_20turbo_20licenses_26',['Complying with the libjpeg-turbo Licenses',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_third_party_libraries_2vtk_2share_2licens57963f20531ea6d6cdca60c5c09bc4ee.html#autotoc_md1031',1,'']]],
  ['the_20modified_203_20clause_20bsd_20license_27',['The Modified (3-clause) BSD License',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_third_party_libraries_2vtk_2share_2licens57963f20531ea6d6cdca60c5c09bc4ee.html#autotoc_md1032',1,'']]],
  ['the_20xmlparser_20library_28',['Debugging with the XMLParser library',['../xmlparser.html#xmlparser_debugging',1,'']]],
  ['the_20xmlparser_20library_20inside_20your_20project_29',['General usage: How to include the XMLParser library inside your project.',['../xmlparser.html#xmlparser_usage',1,'']]],
  ['their_20position_30',['Number of ticks and their position',['../classvtk_axis_actor2_d.html#autotoc_md785',1,'']]],
  ['theora_20packets_31',['Identifying Theora Packets',['../theora_8h.html#identification',1,'']]],
  ['third_20party_20libraries_32',['Third-Party Libraries',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_c_l_a_u_d_e.html#autotoc_md16',1,'']]],
  ['this_20filter_33',['How To Use This Filter',['../classvtk_continuous_scatterplot.html#vtkContinuousScatterplot-how-to-use',1,'']]],
  ['this_20filter_34',['to use this filter',['../classvtk_fiber_surface.html#How',1,'']]],
  ['thread_35',['Thread',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md263',1,'7.1 Main Application Thread'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md486',1,'DCMTK C-FIND Operation (Worker Thread)'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md487',1,'Result Handling (Main Thread)']]],
  ['thread_20safety_36',['Thread Safety',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md70',1,'7. Concurrency &amp;amp; Thread Safety'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_209-_context_manager.html#autotoc_md604',1,'Thread Safety']]],
  ['threading_20in_20device_20package_37',['✅ OBSERVATION: No Threading in Device Package',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md125',1,'']]],
  ['threading_20signal_20slot_20safety_38',['6. Threading &amp;amp; Signal/Slot Safety',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md124',1,'']]],
  ['threads_39',['🔍 LOW: Singleton LoggerProvider accessed from multiple threads',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md73',1,'']]],
  ['three_20licenses_40',['Why Three Licenses?',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_third_party_libraries_2vtk_2share_2licens57963f20531ea6d6cdca60c5c09bc4ee.html#autotoc_md1033',1,'']]],
  ['thumbnail_20panel_20interactions_41',['9.3 Thumbnail Panel Interactions',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md660',1,'']]],
  ['ticks_20and_20their_20position_42',['Number of ticks and their position',['../classvtk_axis_actor2_d.html#autotoc_md785',1,'']]],
  ['time_20manipulation_20routines_43',['Time Manipulation Routines',['../classvtksys_1_1_system_tools.html#autotoc_md1018',1,'']]],
  ['timer_20based_20query_20execution_44',['Timer-Based Query Execution',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md485',1,'']]],
  ['timesteps_45',['Selection TimeSteps',['../classvtk_i_o_s_s_writer.html#SelectionTimeSteps',1,'']]],
  ['to_20byte_20size_20of_20reals_20and_20integers_46',['Properties Related to byte size of reals and integers',['../index.html#autotoc_md997',1,'']]],
  ['to_20dicom_20workflow_47',['MWL to DICOM Workflow',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html#autotoc_md283',1,'']]],
  ['to_20exampage_20ui_48',['Step 1: Add VTK Widget to ExamPage.ui',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md562',1,'']]],
  ['to_20field_20and_20sideset_20surface_20interpretation_49',['Properties related to field and sideset/surface interpretation',['../index.html#autotoc_md998',1,'']]],
  ['to_20include_20the_20xmlparser_20library_20inside_20your_20project_50',['General usage: How to include the XMLParser library inside your project.',['../xmlparser.html#xmlparser_usage',1,'']]],
  ['to_20modify_51',['to Modify',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_211-_procedure-_based-_patient-_addition-_design.html#autotoc_md723',1,'Files to Modify'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_208-_examination-_implementation-_progress.html#autotoc_md574',1,'Phase 2 - Next Files to Modify']]],
  ['to_20read_52',['to read',['../classvtk_i_o_s_s_reader.html#SelectingArrays',1,'Selecting arrays to read'],['../classvtk_i_o_s_s_reader.html#SelectingBlocksSets',1,'Selecting blocks and sets to read']]],
  ['to_20repositories_53',['Epic 8: Connect Configuration Delegates to Repositories',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2docs_2_e_p_i_c___s_t_a_t_u_s___s_u_m_m_a_r_y.html#autotoc_md208',1,'']]],
  ['to_20skew_20grid_54',['Angle from Rectified to Skew Grid',['../classoperation_1_1_conversion.html#angle_from_recitfied_to_skrew_grid',1,'']]],
  ['to_20use_20this_20filter_55',['How To Use This Filter',['../classvtk_continuous_scatterplot.html#vtkContinuousScatterplot-how-to-use',1,'']]],
  ['to_20use_20this_20filter_56',['to use this filter',['../classvtk_fiber_surface.html#How',1,'']]],
  ['to_20write_57',['to write',['../classvtk_i_o_s_s_writer.html#SelectingArraysToWrite',1,'Selecting arrays to write'],['../classvtk_i_o_s_s_writer.html#SelectingBlocksSetsToWrite',1,'Selecting blocks and sets to write']]],
  ['todo_20items_20in_20code_58',['TODO Items (In Code)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md685',1,'']]],
  ['todo_20list_59',['Todo List',['../todo.html',1,'']]],
  ['tool_20interactions_60',['9.1 Tool Interactions',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md658',1,'']]],
  ['tool_20system_61',['5. Tool System',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md634',1,'']]],
  ['tooling_20verification_62',['Tooling Verification',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md85',1,'Phase 5: Tooling &amp;amp; Verification'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md150',1,'Phase 6: Tooling &amp;amp; Verification']]],
  ['tools_63',['Adding New Tools',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_210-_image_viewer-_technical-_documentation.html#autotoc_md682',1,'']]],
  ['tracking_64',['Epic 2: Entity Status Tracking',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2docs_2_e_p_i_c___s_t_a_t_u_s___s_u_m_m_a_r_y.html#autotoc_md174',1,'']]],
  ['trail_65',['3. Audit Trail',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html#autotoc_md344',1,'']]],
  ['trailing_20namespace_20comments_66',['✅ GOOD: No Trailing Namespace Comments',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_device_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md142',1,'']]],
  ['traits_67',['&lt;span class=&quot;tt&quot;&gt;&amp;lt;utils/traits.hpp&amp;gt;&lt;/span&gt; &amp;mdash; Additional type traits',['../namespacediy.html#autotoc_md799',1,'']]],
  ['transfer_20and_20archive_68',['4.8 PACS Transfer and Archive',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html#autotoc_md251',1,'']]],
  ['transient_69',['Workflow Context (Transient)',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md515',1,'']]],
  ['translationprovider_20h_20when_20pointer_20suffices_70',['⚠️ MEDIUM: Multiple headers include &quot;TranslationProvider.h&quot; when pointer suffices',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_core_2_a_u_d_i_t___r_e_p_o_r_t.html#autotoc_md60',1,'']]],
  ['traversal_71',['Traversal',['../classvtk_data_assembly.html#Traversal',1,'']]],
  ['trek_20database_20schema_72',['E-TREK Database Schema',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_202-_database-_schema.html',1,'']]],
  ['trek_20software_20architecture_20document_73',['E-TREK Software Architecture Document',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_201-_architecture-_overview.html',1,'']]],
  ['tupleranges_74',['TupleRanges',['../vtk_data_array_range_8h.html#autotoc_md793',1,'']]],
  ['turbo_20licenses_75',['turbo Licenses',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_third_party_libraries_2vtk_2share_2licens57963f20531ea6d6cdca60c5c09bc4ee.html#autotoc_md1031',1,'Complying with the libjpeg-turbo Licenses'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_third_party_libraries_2vtk_2share_2licens57963f20531ea6d6cdca60c5c09bc4ee.html',1,'libjpeg-turbo Licenses']]],
  ['tutorial_76',['First Tutorial',['../xmlparser.html#xmlparser_tutorial',1,'']]],
  ['tutorial_20and_20many_20examples_20of_20usage_77',['Advanced Tutorial and Many Examples of usage.',['../xmlparser.html#xmlparser_example',1,'']]],
  ['two_20phase_20authentication_78',['Two-Phase Authentication',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md474',1,'']]],
  ['type_20traits_79',['&lt;span class=&quot;tt&quot;&gt;&amp;lt;utils/traits.hpp&amp;gt;&lt;/span&gt; &amp;mdash; Additional type traits',['../namespacediy.html#autotoc_md799',1,'']]],
  ['types_80',['Types',['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_206-_application-_workflows.html#autotoc_md513',1,'Context Types'],['../md__c_1_2_users_2altay_2_one_drive_2_projects_2etrek_2_documents_209-_context_manager.html#autotoc_md589',1,'Context Types'],['../index.html#db_types',1,'Database Types'],['../classvtk_selection_node.html#SelectionTypes',1,'Selection Types'],['../classvtk_extract_block_using_data_assembly.html#vtkExtractBlockUsingDataAssembly-SupportedDataTypes',1,'Supported Data Types']]]
];
